### ISSUE TITLE
Edupi resource URL should be an URL

### ISSUE THREAD

**Issue by rgaudin** [offspot/imager-service#301]
Almost never used the Edupi resource URI (which should be a ZIP file) apparently accepts any string (A user entered “`wikipedia`”) which would fail at the installer's download stage.

We should probably check that:
- It's an URI
- It's reachable at the time of addition (HEAD request)

**Comment by Popolechien** [comment]
Is this still a valid issue since we got rid of Edupi

**Comment by rgaudin** [comment]
It's not valid, not because we got rid of edupi (we still allow pre-populated the filemanager) but because it's been implemented
