### ISSUE TITLE
Default branding option should be Kiwix

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#36]
In case users don't have a favicon and logo at hand, at least the space does not remain empty.
Also, the wording should be clear about it:
"This section allows you to replace some visual elements with your own branding. Currently the Kiwix logo will be used by default".

Kiwix logo can be found at: https://upload.wikimedia.org/wikipedia/commons/1/14/Kiwix_icon.svg

**Comment by kelson42** [comment]
@Popolechien @rgaudin Might be something necessary for offspot.it. First version might not propose any branding configuration?

**Comment by rgaudin** [comment]
Offspot.it won't allow any customization as per specs (initial version).
When there's no customization, branding is already kiwix.
the ticket is about making it clear that if you don't customize, it's OK ; I believe

**Comment by kelson42** [comment]
@rgaudin @Popolechien I believe this has been implemented in new imager if I remind properly, but is that enoughtbtomclose this ticket?

**Comment by rgaudin** [comment]
No, this ticket is about the cardshop showing the actual logo in config_edit so user knows what he can replace (instead of relying on the default). That's a CS UI ticket. Moving it to project.

**Comment by kelson42** [comment]
Ok, then sounds same or similar like #347

**Comment by rgaudin** [comment]
Absolutely
