### ISSUE TITLE
Update pot and french translation

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#368]
Statistiques d'utilisation du Hotspot -> `Basic monitoring tool`

![Capture d’écran 2024-02-01 à 14 01 28](https://github.com/offspot/cardshop/assets/21675885/c0aef06b-1bfd-4949-9371-aeb89ab164a3)

**Comment by rgaudin** [comment]
FR translation hasn't been updated since imager. Every new strings are not translated yet. Turning this ticket into an update one

**Comment by rgaudin** [comment]
Fixed in d47b4ae
