### ISSUE TITLE
Add Prepper box to the sale point

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#396]
Right between Wikipedia and Build-your-own, please add a `Preppers` box priced at 25$ and with the following text:
```
Preppers
For all your SHTF needs
$25
```

Box:
```
* Dozens of resources on homesteading, water treatment, military and emergency medicine, _etc._
* WikiHow, iFixit, and other repair resources
* The entire Wikipedia
* TrailSense and Survival apps for Android, ready to download
Fits on 256 GB microSD card
```

Purchase button points to the`prepper` image on the scheduler

**Comment by rgaudin** [comment]
Done

**Comment by kelson42** [comment]
This is a ticket for kiwix/web IMHO, don't understand why this has been open here!?
