### ISSUE TITLE
download from mirror.download

### ISSUE THREAD

**Issue by rgaudin** [offspot/imager-service#408]
Once we have https://github.com/offspot/offspot-config/issues/39, we should force downloads from mirror.download and not rely on metalink anymore has this proved to be slower in the worker case.
This explains by worker and host being in same DC while metalink downloads from a number of hosts in parallel.

**Comment by kelson42** [comment]
@rgaudin Do you know why this is slower? Sounds strange to me as mirror.download is anyway a source in the Metalink!

**Comment by rgaudin** [comment]
this is not new.
aria2 for metalink assigns parts of the file for the number of source it wants. Parts assigned to mirror.download will be fast but the others will be slower. There would be more parts for that mirror since it would finish them faster but still.

**Comment by rgaudin** [comment]
Done. Readers and ZIM are downloaded from mirror. with Checksum.
