### ISSUE TITLE
Feedback about new beta portal

### ISSUE THREAD

**Issue by kelson42** [offspot/imager-service#409]
It is really better (technology, design) than before, but I see a few things akwards or lacking of polishing which have to be fixed before official release.
_________
Demo branding is missing
http://demo.hotspot.kiwix.org/ welcome page does not have a proeminent name+logo of the product!
http://demo.hotspot.kiwix.org/ welcome page has wrong title, it is "kiwix", it should be "Kiwix Hotspot"
_________
Colorimetry is wrong, why this organge bottom line, it should be grey like the top bar
![image](https://github.com/offspot/imager-service/assets/1029718/4b9a4757-3144-45fa-b233-6f8f2a8c0b2c)
_________
Tiles container top and bottom padding/margin are not the same. Why?
_________
If you want to invite users to click on tiles, somehow you have to show then that they should, like on https://library.kiwix.org.
_________
If you want to allow user to find quickly a content, which I guess this is why you have these "size"/"name" buttons, then just implement a free search text box to apply filter. Here in the demo, this is kind of useless because we have only a few content, but otherwise this seems mandatory.
_________
I have not clue why the size are display on welcome page - with a filter by size. This is completly useless and weird. Obviously on the "download" tab, this makes sense.
_________
Once you have removed the banner for Kiwix download, impossible to show it. This banner is essential here, it should not be removable.
_________
In Kiwix download banner, the name of the product is "Kiwix", not "Kiwix Reader", it's anyway explained on the right what this is about. Please make the logo of Kiwix more proeminent (why so small!!!)
_________
Not clear to me why the "Browse" tab is in tiles mode, and the "Download" tab is in list mode?!... and impossible to change from one mode to the other. This would be far more useful than this "size"/"name" sort buttons IMO.
_________
Download buttons are all broken, impossible to download a ZIM file
_________
I don't understand why, in the tab "download", clicking on an item does not allow to download. It should.
_________
![image](https://github.com/offspot/imager-service/assets/1029718/4fe02fb2-782c-419d-90d0-7cf074a7b561)

Please have no clue what "AF" or "SQ" mean, considering that most of ZIM files are mono-languages and that in worse case, the description gives you a clue, then this is useless. If you believe there is still a problem, then we should have a select box to filter by language. In any case, a tooltip is necessary
_________
Footer bar should have a clear mention of the product (Kiwix Hotspot) with a link to the product page.

**Comment by rgaudin** [comment]
Thank you for this detailed feedback. I opened tickets for all functionnal issues.

Regarding UI/UX, I am surprised to read those comments. We've already been over this but for archive's sake:

- We've agreed that UI/UX is driven by personnal taste for non-professionals.
- We've agreed that only @simsie is skilled in this area.
- We've agreed that decisions were to be made during UI meetings which were composed of:
  - @simsie proposing mockups and _vision_
  - @Popolechien defending strategy and target users' POV
  - @rgaudin making sure implementation effort is reasonable given our time and skills constraints
  - Consensus based

This was for the initial design effort. For maintenance, I think the process should be:

- User opening individual, argued tickets
- @simsie responding to them so we don't drift away from the original strategy and the general cohesion we're trying to bring.
- Fix by dev depending on discussion.

---

> Demo branding is missing http://demo.hotspot.kiwix.org/ welcome page does not have a proeminent name+logo of the product!

This is not linked to the dashboard. @Popolechien created an image without branding. What you see here is the default branding of an hotspot.

I don't know if @Popolechien left it out on purpose but I'm not sure what “demo branding” would be if not. I don't think we discussed it but I agree it would be for the best.

>  http://demo.hotspot.kiwix.org/ welcome page has wrong title, it is "kiwix", it should be "Kiwix Hotspot"

Opened https://github.com/offspot/container-images/issues/52

> If you want to invite users to click on tiles, somehow you have to show then that they should, like on https://library.kiwix.org.

I don't understand this statement. library.kiwix.org have tiles change and cursor pointer on hover. Is that what you are referring to? Dashboard has cursor pointer and color change.

> Once you have removed the banner for Kiwix download, impossible to show it. This banner is essential here, it should not be removable.

Opened https://github.com/offspot/container-images/issues/53

> In Kiwix download banner, the name of the product is "Kiwix", not "Kiwix Reader", it's anyway explained on the right what this is about. 

Opened https://github.com/offspot/container-images/issues/54

> Download buttons are all broken, impossible to download a ZIM file
> I don't understand why, in the tab "download", clicking on an item does not allow to download. It should.

Opened https://github.com/offspot/container-images/issues/55


> Please have no clue what "AF" or "SQ" mean, considering that most of ZIM files are mono-languages and that in worse case, the description gives you a clue, then this is useless.

In this case, ZIM metadata is misleading in that it lists all 105 supported languages [alphabetically](https://kiwix.demo.hotspot.kiwix.org/raw/kiwix_phets_mul_all_/meta/Language), in contradiction with the spec.

> If you believe there is still a problem, then we should have a select box to filter by language.

There's already a language filter. 😵‍💫

> In any case, a tooltip is necessary

Opened https://github.com/offspot/container-images/issues/56

> Footer bar should have a clear mention of the product (Kiwix Hotspot) with a link to the product page.

Opened https://github.com/offspot/container-images/issues/57

**Comment by rgaudin** [comment]
I think this one can be closed now.
