### ISSUE TITLE
User unable to access captive portal or hotspot

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#415]
From user:

> I purchased and downloaded the image which I’ve successfully burned to an sdcard which I’ve booted in my Pi.
After a few minutes, the hotspot ‘ready’ appears, which I can connect to, however, I cannot connect to any information, I have also tried connecting to 192.168.2.1 which is the gateway, dhcp & dns server on the Pi. 
> I have read the FAQ and also the info in the email that came with the link but I cannot gain access. 
I’ve tried via a Windows laptop and an iPhone, latest OS’s on both, same result.  I’ve also tried different browsers and disabling the private IP setting. 
I’ve tried a Pi 4 & Pi 3. 

The fact that `ready` appears seems to indicate that the image is working as intended, but I have no idea what could be wrong on the user side.

**Comment by rgaudin** [comment]
Please ask user to add more details here (seems tech savvy) as “I cannot connect to any information” is too vague to be useful here. What's happening? Error message?

**Comment by Popolechien** [comment]
Nothing happens apparently. No captive portal, and going to http://ready.hotspot returns nothing.

**Comment by rgaudin** [comment]
OK ; investigating

**Comment by Popolechien** [comment]
I am reopening this issue as the user is still unable to access the contents of the card. Adding a few screenshots he took while trying the latest image we sent them:
<img src="https://github.com/offspot/imager-service/assets/21675885/fd93270f-c258-4e09-a090-824bcaccf824" width=300>
<img src="https://github.com/offspot/imager-service/assets/21675885/5acdea42-c6fb-4429-9114-1e29dd4325b7" width=300>
<img src="https://github.com/offspot/imager-service/assets/21675885/3a188a19-58db-46dc-8084-8960ac9a0c90" width=300>

Any idea?

**Comment by rgaudin** [comment]
This is exactly what was happening: WiFi network is visible but the captive portal is not triggered when connecting to it…

Can you make sure User is testing with a card **recreated** after **downloading** the new Image (which was uploaded on Wed, 01 May 2024 14:49:11 GMT)

Just tested with a similar image (not the same, too large to download) ; works as expected.

**Comment by Popolechien** [comment]
> Can you make sure User is testing with a card recreated after downloading the new Image (which was uploaded on Wed, 01 May 2024 14:49:11 GMT)

Yep, download link was sent on 2 May at 6:28pm.

**Comment by rgaudin** [comment]
OK, I think it would be good for you @Popolechien to download the exact same file and test it just to rule out an image issue. Please.

I see that he tested on Pi3 and Pi4 and also multiple clients which is good.

Please check Power Supply capacity. Pi3 should be at least 2.5A (12.5W) and Pi4 3A (15W)
If it complies, make sure the card was written properly: using raspberrypi imager, and letting it finish the _Verify_ part. He can just reflash the same card with that image if unsure whether this was done.

If this leads nowhere, we'd have to get some diagnosis information either by plugging the Pi into a screen or connecting the Pi to an ethernet network and running some commands.

**Comment by Popolechien** [comment]
Yup. I've had him download another, 8GB test image just to see if that fails as well.

**Comment by rgaudin** [comment]
Thank you ; glad you tested it.

I think we have a ticket regarding first-time and boot-time in general experience. As already explained, we startup the WiFi AP very early, when the rest if not ready and we provide no feedback when things are ready.

**Comment by kelson42** [comment]
It seems very important that the benchmark tests tests a minima the captive portal. It seems critical and I see no other place where it could be done.

**Comment by Popolechien** [comment]
Turns out that verification at the end of the Raspberry Pi Imager flash failed twice in a row: user bought a new card and things worked like a charm.

**Comment by rgaudin** [comment]
Ok good to know.
