### ISSUE TITLE
What is the ideal amount of RAM for a Raspberry Pi hotspot (with Wikipedia Full Size)

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#419]
The question came from a user that enquired about Raspberry Pi zero 2W. Not sure there is a straightforward answer but worth asking.

**Comment by rgaudin** [comment]
It's related to the number of services (ours and _Learning tools_) and the number of ZIM files. Size of ZIM files dont matter much.

**Comment by Popolechien** [comment]
Ah my bad then, I thought that the entire Wikipedia in English was an issue because of the size of the index or something. Thanks.

**Comment by rgaudin** [comment]
If you want additional details (might be interesting to document it), ask for details in libzim.

**Comment by rgaudin** [comment]
and/or libkiwix as what's important is the reader opening multiple files as once
