### ISSUE TITLE
Packages are listed in MB/GB while content files are MiB/GiB

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#429]
Pretty much what it says on the title: units are not consistent
![Screenshot 2024-06-25 at 10 52 31](https://github.com/offspot/imager-service/assets/21675885/ab48014e-f6c2-4cb0-a78f-8f5407118b7a)
![Screenshot 2024-06-25 at 10 52 50](https://github.com/offspot/imager-service/assets/21675885/cbeea0c4-95aa-4f3f-ab89-e4dcb2b7f347)

**Comment by rgaudin** [comment]
🤯

**Comment by kelson42** [comment]
LOL

**Comment by rgaudin** [comment]
Was even worst: same page two columns with similar content but diffrent units…

<img width="1248" alt="Screenshot 2024-06-25 at 10 08 42" src="https://github.com/offspot/imager-service/assets/57929/a644c37a-846f-4bca-9023-c2a3e34a11a8">

Was actually a typo as this is a simple human display in JS. Was already MiB but displayed as MB.

Note that we always use binary (MiB) for content but always powers of 10 (MB) for Media (SD-card) as those are sold using GB values

**Comment by Popolechien** [comment]
Well I'm sure it only was a recent issue and not something that's been arount for the past six months (or 4 years) 😁

**Comment by rgaudin** [comment]
Well, you know, there's absolutely no technical way to find out 😅😬🫣
