### ISSUE TITLE
Update `KIWIX_READERS_SOURCES` with version 3.11.1 of kiwix android app.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [offspot/imager-service#430]
We have released the version [3.11.1](https://download.kiwix.org/release/kiwix-android/kiwix-3.11.1.apk) for the kiwix android, please update it in [KIWIX_READERS_SOURCES](https://github.com/offspot/imager-service/blob/096d19fc61d3461aefdcd79017e0b05a9ecf81c5/manager/manager/settings.py#L236C1-L236C22)

**Comment by rgaudin** [comment]
Already! Thank you

**Comment by rgaudin** [comment]
Fixed in 9ad3519
