### ISSUE TITLE
unable to unselect beta feature

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#434]
When beta features are unabled and the new dashboard is selected, I appear to be unable to unselect it.
![Screenshot 2024-07-04 at 14 34 30](https://github.com/offspot/imager-service/assets/21675885/d9178a1d-ab33-4ce6-8a67-7b61cb689f28)

**Comment by rgaudin** [comment]
block should not appear at all I think. thanks

**Comment by rgaudin** [comment]
After careful testing, I believe you had beta enabled 😆 Closing
