### ISSUE TITLE
Branding is unavailable

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#438]
I created configuration https://imager.kiwix.org/configurations/915 which includes a client logo (FO). But when running said config onto demo.hotspot.kiwix.org I end up with the Kiwix logo.

Am currently re-running the config with a freshly uploaded logo as this one was created before the update to 3.0.
![Screenshot 2024-07-12 at 12 16 25](https://github.com/user-attachments/assets/b26232b3-ae62-4c84-8887-104fe62182c5)

**Comment by rgaudin** [comment]
If I found the correct order it does reference a logo so that would be a bug. Will check next week

**Comment by Popolechien** [comment]
Just in case and to confirm it was this one [here](https://imager.kiwix.org/all-orders/668fa03e90882ec51748c65c) and it does list the correct logo `orange-fondation.png ` in the config display.

**Comment by Popolechien** [comment]
Seems now ok.
I had reused an old / existing config. Re-uploaded the image.
