### ISSUE TITLE
Prepper download not working

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#439]
When trying to download the torrent we get the following error

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>preppers_2024-06_665c36e956.img.torrent</Key>
<RequestId>946F46E70B08C5E0:B</RequestId>
<HostId>JSF1KSk6RGe1bxll9jXf/VR3PBrWl7DUJOt6ep/kSD/4MVxgQXGtPwBYDsYnX3vxidVuDWh6TeCo</HostId>
<CMReferenceId>MTcyMDg0ODM0NjMxNyAzOC4xNDYuNDAuMTExIENvbklEOjgyODMzMzMxL0VuZ2luZUNvbklEOjEwNTkxODMvQ29yZTo1MQ==</CMReferenceId>
</Error>
```

This only seems to affect the Prepper image. 

I have restarted the imager to see if that changes anything.

**Comment by Popolechien** [comment]
Created a new image that works (downloading the torrent from the confirmation email), but trying to get it from the scheduler returns the same error.

**Comment by rgaudin** [comment]
this is the june image which is obsolete. you seem to be using an old link.

I understand you get the error by clicking on "redirect" link in scheduler page and that restarted imager mean recreated the image, right?

**Comment by rgaudin** [comment]
ps ; you again created peepers and computers as not private. please fix that first

**Comment by Popolechien** [comment]
> this is the june image which is obsolete. you seem to be using an old link.

I took the link straight from the scheduler yes, but the initial report came from two separate users who purchased the image last night.

**Comment by rgaudin** [comment]
Ok I believe the redirect is what we use in the shop. please recreate as private and retest

**Comment by Popolechien** [comment]
Seems to be working now (and set to private). Thanks.
