### ISSUE TITLE
Beta dashboard is missing

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#440]
Ran https://imager.kiwix.org/all-orders/6691031290882e00251a4f28 that included the new dashboard, but as shown at demo.hotspot.kiwix.org the feature is not enabled.

**Comment by rgaudin** [comment]
If beta was not enabled on the organization at time of order, no beta feature will be included in image, as clearly explained in beta page.

I believe that's what happened here (please confirm).

the somewhat human json config summary is probably simply displaying what's in the DB and not taking this into account. To be fixed obviously

**Comment by Popolechien** [comment]
I'm pretty confident it was enabled, but I'll try again.

**Comment by Popolechien** [comment]
My bad, it's there and working.
