### ISSUE TITLE
Update download message to recommend RPi imager instead of etcher

### ISSUE THREAD

**Issue by Popolechien** [offspot/imager-service#444]
Made a PR for scheduler/src/templates/recipient_image_uploaded_public.html and noticed the following piece of code:

> To install the file onto a microSD card, we recommend using %(etcher_link)s.")|format(etcher_link=etcher_link)|safe }}

Not sure where etcher points at but haven't we moved to recommending the Raspberry Pi imager?

**Comment by rgaudin** [comment]
Well that's the magic of variables 😉 We just changed the value when we switched to PI Imager

```
{% set etcher_link %}<a href="https://www.raspberrypi.com/software/">Raspberry Pi Imager</a>{% endset %}
```

**Comment by Popolechien** [comment]
I figured that much but one never knows ¯\_(ツ)_/¯
